[[main]]
  name = "Вконтакте"
  url = "https://vk.com/restinkhakassia"
  weight = 10

[[social]]
  name = "Инстаграм"
  url = "https://instagram.com/malaya_siya"
  weight = 20

[[social]]
  name = "Телефон"
  url = "tel:+79130597432"
  weight = 30
