title = "ГОСТИНЫЙ ДВОР"
titleSeparator = "-"
titleAddition = "УЮТНЫЙ ОТДЫХ В ХАКАСИИ"
description = "Малая Сыя | Гостиный двор | Отдых в Хакасии 2021"

images = ["t4WMyHyaVxg.png"]

twitterSite = "@slv"
twitterCreator = "@slv"
facebookAuthor = "slv"
facebookPublisher = "slv"
ogLocale = "en_US"

schemaType = "Organization"
schemaLogo = "logo-hyas.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/h-enk"
schemaSection = "blog1"

siteLinksSearchBox = true

themeColor = "#fff"

quality = 85
bgColor = "#fff"
landscapePhotoWidths = [1000, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500, 200]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://gethyas.com/\">Hyas</a>"

alert = false
alertText = "Deliver web projects 10x faster. <a class=\"alert-link\" href=\"https://www.netlify.com/whitepaper/\" target=\"_blank\" rel=\"noopener\">Get the free enterprise paper →</a>"
