baseurl                  = "http://malayasiya.netlify.app"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "ru"
isMultilingual           = false
title                    = "ГОСТИНЫЙ ДВОР"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon May 02, 2021"
    dateformfull         = "Mon May 2 2021 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "Главная"                           # What to call the home page link, link will not be rendered if empty
    footerText           = "Малая Сыя | Гостиный двор | Отдых в Хакасии 2021"

# Metadata for Open Graph and Twitter
    description          = "Малая Сыя | Гостиный двор | Отдых в Хакасии 2021"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Малая Сыя | Гостиный двор | Отдых в Хакасии 2021"
    # rss                = ""

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "gallery"
    text = "Галерея"

[[params.mainMenu]]
    link = "about"
    text = "О нас"

[imaging]
    quality = 75
